backend:
  name: github
  repo: SRC-Arts/SRC-Arts.github.io
  branch: main
  client_id: YOUR_CLIENT_ID
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "uploads" # where uploaded images will go
public_folder: "/uploads"

collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Date", name: "date", widget: "datetime" }

